disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - unused_optional_binding
  - vertical_whitespace
  - trailing_whitespace
  - trailing_newline

excluded:
  - Pods