on: [pull_request]
jobs:
  buildAndTest: 
    runs-on: macos-latest
    steps: 
     - uses: actions/checkout@v2
     - uses: actions/cache@v2
       with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
     - name: CocoaPod Install
       run: 
        pod install
     - name: Running test 🧪
       env:
         CLIENT_ID_GITHUB: ${{ secrets.CLIENT_ID_GITHUB }}
         CLIENT_SECRET_GITHUB: ${{ secrets.CLIENT_SECRET_GITHUB }}
       run:
        xcodebuild test -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 12' -workspace PRTracker.xcworkspace -scheme PRTracker
